In [ ]:
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
data_prices= pd.read_csv ("Alternating Framework.csv")
data_prices

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-05-16,33.660000,34.500000,33.080002,34.040001,34.040001,4267500
1,2019-05-17,33.560001,35.060001,33.500000,34.610001,34.610001,4496400
2,2019-05-20,34.130001,34.689999,34.009998,34.660000,34.660000,2017000
3,2019-05-21,34.919998,35.290001,34.750000,34.860001,34.860001,2028200
4,2019-05-22,34.750000,35.389999,34.669998,35.250000,35.250000,1726500
...,...,...,...,...,...,...,...
1255,2024-05-10,49.110001,49.360001,48.549999,49.099998,49.099998,955200
1256,2024-05-13,49.099998,49.669998,48.549999,48.570000,48.570000,967100
1257,2024-05-14,49.110001,49.540001,48.689999,48.730000,48.730000,1290400
1258,2024-05-15,48.779999,49.470001,48.240002,49.320000,49.320000,1255400
1259,2024-05-16,49.680000,49.480000,49.020000,49.185001,49.185001,673154

In [ ]:
benchmark_value = ((data_prices["Close"].iloc[1259]-data_prices["Close"].iloc[0])/(data_prices["Close"].iloc[0]))*10000
benchmark_value

4449.177307603488

In [ ]:
def s12(data):
  s12=[]
  sum=0

  for i in range (11):
    s12.append(0)
    sum+=data['Close'].iloc[i]

  sum+=data['Close'].iloc[11]
  s12.append(sum/12)

  for i in range (12,len(data)):
    sum+= data['Close'].iloc[i]
    sum-= data['Close'].iloc[i-12]
    s12.append(sum/12)

  data['s12']=s12

  return data

In [ ]:
data_prices=s12(data_prices)
data_prices

,Date,Open,High,Low,Close,Adj Close,Volume,s12
0,2019-05-16,33.660000,34.500000,33.080002,34.040001,34.040001,4267500,0.000000
1,2019-05-17,33.560001,35.060001,33.500000,34.610001,34.610001,4496400,0.000000
2,2019-05-20,34.130001,34.689999,34.009998,34.660000,34.660000,2017000,0.000000
3,2019-05-21,34.919998,35.290001,34.750000,34.860001,34.860001,2028200,0.000000
4,2019-05-22,34.750000,35.389999,34.669998,35.250000,35.250000,1726500,0.000000
...,...,...,...,...,...,...,...,...
1255,2024-05-10,49.110001,49.360001,48.549999,49.099998,49.099998,955200,47.681666
1256,2024-05-13,49.099998,49.669998,48.549999,48.570000,48.570000,967100,47.922500
1257,2024-05-14,49.110001,49.540001,48.689999,48.730000,48.730000,1290400,48.099166
1258,2024-05-15,48.779999,49.470001,48.240002,49.320000,49.320000,1255400,48.312500
1259,2024-05-16,49.680000,49.480000,49.020000,49.185001,49.185001,673154,48.558750

In [ ]:
def s26(data):
  s26=[]
  sum=0

  for i in range (25):
    s26.append(0)
    sum+=data['Close'].iloc[i]

  sum+=data['Close'].iloc[25]
  s26.append(sum/26)

  for i in range (26,len(data)):
    sum+= data['Close'].iloc[i]
    sum-= data['Close'].iloc[i-26]
    s26.append(sum/26)

  data['s26']=s26

  return data

In [ ]:
data_prices=s26(data_prices)
data_prices

,Date,Open,High,Low,Close,Adj Close,Volume,s12,s26
0,2019-05-16,33.660000,34.500000,33.080002,34.040001,34.040001,4267500,0.000000,0.000000
1,2019-05-17,33.560001,35.060001,33.500000,34.610001,34.610001,4496400,0.000000,0.000000
2,2019-05-20,34.130001,34.689999,34.009998,34.660000,34.660000,2017000,0.000000,0.000000
3,2019-05-21,34.919998,35.290001,34.750000,34.860001,34.860001,2028200,0.000000,0.000000
4,2019-05-22,34.750000,35.389999,34.669998,35.250000,35.250000,1726500,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
1255,2024-05-10,49.110001,49.360001,48.549999,49.099998,49.099998,955200,47.681666,46.521923
1256,2024-05-13,49.099998,49.669998,48.549999,48.570000,48.570000,967100,47.922500,46.559615
1257,2024-05-14,49.110001,49.540001,48.689999,48.730000,48.730000,1290400,48.099166,46.606923
1258,2024-05-15,48.779999,49.470001,48.240002,49.320000,49.320000,1255400,48.312500,46.669615
1259,2024-05-16,49.680000,49.480000,49.020000,49.185001,49.185001,673154,48.558750,46.763654

In [ ]:
def e12(data):
  e12=[]

  for i in range (11):
    e12.append(0)

  e12.append(data['s12'].iloc[11])

  f= 2/(12+1)

  for i in range (12,len(data)):
    ema = data['Close'].iloc[i]*f + e12[-1]*(1-f)
    e12.append(ema)

  data['e12']=e12

  return data

In [ ]:
data_prices=e12(data_prices)
data_prices

,Date,Open,High,Low,Close,Adj Close,Volume,s12,s26,e12
0,2019-05-16,33.660000,34.500000,33.080002,34.040001,34.040001,4267500,0.000000,0.000000,0.000000
1,2019-05-17,33.560001,35.060001,33.500000,34.610001,34.610001,4496400,0.000000,0.000000,0.000000
2,2019-05-20,34.130001,34.689999,34.009998,34.660000,34.660000,2017000,0.000000,0.000000,0.000000
3,2019-05-21,34.919998,35.290001,34.750000,34.860001,34.860001,2028200,0.000000,0.000000,0.000000
4,2019-05-22,34.750000,35.389999,34.669998,35.250000,35.250000,1726500,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...
1255,2024-05-10,49.110001,49.360001,48.549999,49.099998,49.099998,955200,47.681666,46.521923,47.893905
1256,2024-05-13,49.099998,49.669998,48.549999,48.570000,48.570000,967100,47.922500,46.559615,47.997920
1257,2024-05-14,49.110001,49.540001,48.689999,48.730000,48.730000,1290400,48.099166,46.606923,48.110548
1258,2024-05-15,48.779999,49.470001,48.240002,49.320000,49.320000,1255400,48.312500,46.669615,48.296617
1259,2024-05-16,49.680000,49.480000,49.020000,49.185001,49.185001,673154,48.558750,46.763654,48.433292

In [ ]:
def e26(data):
  e26=[]

  for i in range (25):
    e26.append(0)

  e26.append(data['s26'].iloc[25])

  f= 2/(26+1)  #

  for i in range (26,len(data)):
    ema = data['Close'].iloc[i]*f + e26[-1]*(1-f)
    e26.append(ema)

  data['e26']=e26

  return data

In [ ]:
data_prices=e26(data_prices)
data_prices

,Date,Open,High,Low,Close,Adj Close,Volume,s12,s26,e12,e26
0,2019-05-16,33.660000,34.500000,33.080002,34.040001,34.040001,4267500,0.000000,0.000000,0.000000,0.000000
1,2019-05-17,33.560001,35.060001,33.500000,34.610001,34.610001,4496400,0.000000,0.000000,0.000000,0.000000
2,2019-05-20,34.130001,34.689999,34.009998,34.660000,34.660000,2017000,0.000000,0.000000,0.000000,0.000000
3,2019-05-21,34.919998,35.290001,34.750000,34.860001,34.860001,2028200,0.000000,0.000000,0.000000,0.000000
4,2019-05-22,34.750000,35.389999,34.669998,35.250000,35.250000,1726500,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
1255,2024-05-10,49.110001,49.360001,48.549999,49.099998,49.099998,955200,47.681666,46.521923,47.893905,47.684343
1256,2024-05-13,49.099998,49.669998,48.549999,48.570000,48.570000,967100,47.922500,46.559615,47.997920,47.749948
1257,2024-05-14,49.110001,49.540001,48.689999,48.730000,48.730000,1290400,48.099166,46.606923,48.110548,47.822544
1258,2024-05-15,48.779999,49.470001,48.240002,49.320000,49.320000,1255400,48.312500,46.669615,48.296617,47.933467
1259,2024-05-16,49.680000,49.480000,49.020000,49.185001,49.185001,673154,48.558750,46.763654,48.433292,48.026173

In [ ]:
macd=[]

for i in range (0,25):
    macd.append(0)

for i in range(25,len(data_prices)):
    macd.append(data_prices['e12'].iloc[i]-data_prices['e26'].iloc[i])

data_prices["macd"]=macd
data_prices

,Date,Open,High,Low,Close,Adj Close,Volume,s12,s26,e12,e26,macd
0,2019-05-16,33.660000,34.500000,33.080002,34.040001,34.040001,4267500,0.000000,0.000000,0.000000,0.000000,0.000000
1,2019-05-17,33.560001,35.060001,33.500000,34.610001,34.610001,4496400,0.000000,0.000000,0.000000,0.000000,0.000000
2,2019-05-20,34.130001,34.689999,34.009998,34.660000,34.660000,2017000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2019-05-21,34.919998,35.290001,34.750000,34.860001,34.860001,2028200,0.000000,0.000000,0.000000,0.000000,0.000000
4,2019-05-22,34.750000,35.389999,34.669998,35.250000,35.250000,1726500,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
1255,2024-05-10,49.110001,49.360001,48.549999,49.099998,49.099998,955200,47.681666,46.521923,47.893905,47.684343,0.209562
1256,2024-05-13,49.099998,49.669998,48.549999,48.570000,48.570000,967100,47.922500,46.559615,47.997920,47.749948,0.247972
1257,2024-05-14,49.110001,49.540001,48.689999,48.730000,48.730000,1290400,48.099166,46.606923,48.110548,47.822544,0.288003
1258,2024-05-15,48.779999,49.470001,48.240002,49.320000,49.320000,1255400,48.312500,46.669615,48.296617,47.933467,0.363150
1259,2024-05-16,49.680000,49.480000,49.020000,49.185001,49.185001,673154,48.558750,46.763654,48.433292,48.026173,0.407119

In [ ]:
def s9(data):
  s9=[]
  sum=0

  for i in range (33):
    s9.append(0)
    sum+=data['macd'].iloc[i]

  sum+=data['macd'].iloc[33]
  s9.append(sum/9)

  for i in range (34,len(data)):
    sum+= data['macd'].iloc[i]
    sum-= data['macd'].iloc[i-9]
    s9.append(sum/9)

  data['s9']=s9

  return data

In [ ]:
data_prices=s9(data_prices)
data_prices

,Date,Open,High,Low,Close,Adj Close,Volume,s12,s26,e12,e26,macd,s9
0,2019-05-16,33.660000,34.500000,33.080002,34.040001,34.040001,4267500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2019-05-17,33.560001,35.060001,33.500000,34.610001,34.610001,4496400,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2019-05-20,34.130001,34.689999,34.009998,34.660000,34.660000,2017000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2019-05-21,34.919998,35.290001,34.750000,34.860001,34.860001,2028200,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2019-05-22,34.750000,35.389999,34.669998,35.250000,35.250000,1726500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255,2024-05-10,49.110001,49.360001,48.549999,49.099998,49.099998,955200,47.681666,46.521923,47.893905,47.684343,0.209562,-0.434115
1256,2024-05-13,49.099998,49.669998,48.549999,48.570000,48.570000,967100,47.922500,46.559615,47.997920,47.749948,0.247972,-0.277041
1257,2024-05-14,49.110001,49.540001,48.689999,48.730000,48.730000,1290400,48.099166,46.606923,48.110548,47.822544,0.288003,-0.132206
1258,2024-05-15,48.779999,49.470001,48.240002,49.320000,49.320000,1255400,48.312500,46.669615,48.296617,47.933467,0.363150,-0.001182
1259,2024-05-16,49.680000,49.480000,49.020000,49.185001,49.185001,673154,48.558750,46.763654,48.433292,48.026173,0.407119,0.114028

In [ ]:
def e9(data):
  e9=[]

  for i in range (33):
    e9.append(0)

  e9.append(data['s9'].iloc[33])

  f= 2/(9+1)  #

  for i in range (34,len(data)):
    ema = data['s9'].iloc[i]*f + e9[-1]*(1-f)
    e9.append(ema)

  data['e9']=e9

  return data

In [ ]:
data_prices=e9(data_prices)
data_prices

,Date,Open,High,Low,Close,Adj Close,Volume,s12,s26,e12,e26,macd,s9,e9
0,2019-05-16,33.660000,34.500000,33.080002,34.040001,34.040001,4267500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2019-05-17,33.560001,35.060001,33.500000,34.610001,34.610001,4496400,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2019-05-20,34.130001,34.689999,34.009998,34.660000,34.660000,2017000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2019-05-21,34.919998,35.290001,34.750000,34.860001,34.860001,2028200,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2019-05-22,34.750000,35.389999,34.669998,35.250000,35.250000,1726500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255,2024-05-10,49.110001,49.360001,48.549999,49.099998,49.099998,955200,47.681666,46.521923,47.893905,47.684343,0.209562,-0.434115,-1.023310
1256,2024-05-13,49.099998,49.669998,48.549999,48.570000,48.570000,967100,47.922500,46.559615,47.997920,47.749948,0.247972,-0.277041,-0.874056
1257,2024-05-14,49.110001,49.540001,48.689999,48.730000,48.730000,1290400,48.099166,46.606923,48.110548,47.822544,0.288003,-0.132206,-0.725686
1258,2024-05-15,48.779999,49.470001,48.240002,49.320000,49.320000,1255400,48.312500,46.669615,48.296617,47.933467,0.363150,-0.001182,-0.580785
1259,2024-05-16,49.680000,49.480000,49.020000,49.185001,49.185001,673154,48.558750,46.763654,48.433292,48.026173,0.407119,0.114028,-0.441822

In [ ]:
def s25(data):
  s25=[]
  sum=0

  for i in range (24):
    s25.append(0)
    sum+=data['Close'].iloc[i]

  sum+=data['Close'].iloc[24]
  s25.append(sum/25)

  for i in range (25,len(data)):
    sum+= data['Close'].iloc[i]
    sum-= data['Close'].iloc[i-25]
    s25.append(sum/25)

  data['s25']=s25

  return data

In [ ]:
data_prices=s25(data_prices)
data_prices

,Date,Open,High,Low,Close,Adj Close,Volume,s12,s26,e12,e26,macd,s9,e9,s25
0,2019-05-16,33.660000,34.500000,33.080002,34.040001,34.040001,4267500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
1,2019-05-17,33.560001,35.060001,33.500000,34.610001,34.610001,4496400,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
2,2019-05-20,34.130001,34.689999,34.009998,34.660000,34.660000,2017000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
3,2019-05-21,34.919998,35.290001,34.750000,34.860001,34.860001,2028200,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
4,2019-05-22,34.750000,35.389999,34.669998,35.250000,35.250000,1726500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255,2024-05-10,49.110001,49.360001,48.549999,49.099998,49.099998,955200,47.681666,46.521923,47.893905,47.684343,0.209562,-0.434115,-1.023310,46.4792
1256,2024-05-13,49.099998,49.669998,48.549999,48.570000,48.570000,967100,47.922500,46.559615,47.997920,47.749948,0.247972,-0.277041,-0.874056,46.5220
1257,2024-05-14,49.110001,49.540001,48.689999,48.730000,48.730000,1290400,48.099166,46.606923,48.110548,47.822544,0.288003,-0.132206,-0.725686,46.5636
1258,2024-05-15,48.779999,49.470001,48.240002,49.320000,49.320000,1255400,48.312500,46.669615,48.296617,47.933467,0.363150,-0.001182,-0.580785,46.6668
1259,2024-05-16,49.680000,49.480000,49.020000,49.185001,49.185001,673154,48.558750,46.763654,48.433292,48.026173,0.407119,0.114028,-0.441822,46.7502

In [ ]:
from math import sqrt

def dev(data):
  dev=[]
  sum=0

  for i in range (24):
    dev.append(0)
    sum+= data['Close'].iloc[i]**2


  sum+=data['Close'].iloc[24]**2
  dev.append(sqrt((sum/25)-data['s25'].iloc[24]**2))

  for i in range (25,len(data)):
    sum+= data['Close'].iloc[i]**2
    sum-= data['Close'].iloc[i-25]**2
    dev.append(sqrt((sum/25)-data['s25'].iloc[i]**2))

  data['dev']=dev

  return data

In [ ]:
data_prices=dev(data_prices)
data_prices

,Date,Open,High,Low,Close,Adj Close,Volume,s12,s26,e12,e26,macd,s9,e9,s25,dev
0,2019-05-16,33.660000,34.500000,33.080002,34.040001,34.040001,4267500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
1,2019-05-17,33.560001,35.060001,33.500000,34.610001,34.610001,4496400,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
2,2019-05-20,34.130001,34.689999,34.009998,34.660000,34.660000,2017000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
3,2019-05-21,34.919998,35.290001,34.750000,34.860001,34.860001,2028200,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
4,2019-05-22,34.750000,35.389999,34.669998,35.250000,35.250000,1726500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255,2024-05-10,49.110001,49.360001,48.549999,49.099998,49.099998,955200,47.681666,46.521923,47.893905,47.684343,0.209562,-0.434115,-1.023310,46.4792,1.746076
1256,2024-05-13,49.099998,49.669998,48.549999,48.570000,48.570000,967100,47.922500,46.559615,47.997920,47.749948,0.247972,-0.277041,-0.874056,46.5220,1.783291
1257,2024-05-14,49.110001,49.540001,48.689999,48.730000,48.730000,1290400,48.099166,46.606923,48.110548,47.822544,0.288003,-0.132206,-0.725686,46.5636,1.821768
1258,2024-05-15,48.779999,49.470001,48.240002,49.320000,49.320000,1255400,48.312500,46.669615,48.296617,47.933467,0.363150,-0.001182,-0.580785,46.6668,1.900224
1259,2024-05-16,49.680000,49.480000,49.020000,49.185001,49.185001,673154,48.558750,46.763654,48.433292,48.026173,0.407119,0.114028,-0.441822,46.7502,1.962153

In [ ]:
t_f = 1.4
s_l = 0.8

In [ ]:
def strat1(start,end,non_invested):
  current=0
  returns=0
  stocks=0
  buy=0
  for i in range(start,end+1):
    if(buy>0 and data_prices['Close'].iloc[i]>t_f*buy):
      if(current==-1):
        non_invested-=stocks*data_prices['Close'].iloc[i]
        stocks=0
        current=0
        buy=0
      elif(current==1):
        non_invested+=stocks*data_prices['Close'].iloc[i]
        stocks=0
        current=0
        buy=0
    elif(buy>0 and data_prices['Close'].iloc[i]<s_l*buy):
      if(current==-1):
        non_invested-=stocks*data_prices['Close'].iloc[i]
        stocks=0
        current=0
        buy=0
      elif(current==1):
        non_invested+=stocks*data_prices['Close'].iloc[i]
        stocks=0
        current=0
        buy=0
    elif((data_prices['macd'].iloc[i]<data_prices['e9'].iloc[i] and data_prices['macd'].iloc[i-1]>data_prices['e9'].iloc[i-1] )and current==0):
      start=i
      current=-1
      value = non_invested/data_prices['Close'].iloc[i]
      result = math.floor(value)
      stocks= result
      buy=data_prices['Close'].iloc[i]
      non_invested += result*data_prices['Close'].iloc[i]
    elif((data_prices['macd'].iloc[i]>data_prices['e9'].iloc[i] and data_prices['macd'].iloc[i-1]<data_prices['e9'].iloc[i-1] )and current==0):
      start=i
      current=1
      value = non_invested/data_prices['Close'].iloc[i]
      result = math.floor(value)
      stocks= result
      buy=data_prices['Close'].iloc[i]
      non_invested -= result*data_prices['Close'].iloc[i]
    elif((data_prices['macd'].iloc[i]>data_prices['e9'].iloc[i] and data_prices['macd'].iloc[i-1]<data_prices['e9'].iloc[i-1] )and current==-1):
      non_invested-=stocks*data_prices['Close'].iloc[i]
      stocks=0
      current=0
    elif((data_prices['macd'].iloc[i]<data_prices['e9'].iloc[i] and data_prices['macd'].iloc[i-1]>data_prices['e9'].iloc[i-1] )and current==1):
      non_invested+=stocks*data_prices['Close'].iloc[i]
      stocks=0
      current=0

  if(current==1):
   non_invested +=stocks*data_prices['Close'].iloc[end]
  if(current==-1):
   non_invested -=stocks*data_prices['Close'].iloc[end]

  return non_invested

In [ ]:
def strat2(start,end,non_invested):
  current=0
  returns=0
  stocks=0
  buy=0
  for i in range(start,end+1):
    if(buy>0 and data_prices['Close'].iloc[i]>t_f*buy):
      if(current==-1):
        non_invested-=stocks*data_prices['Close'].iloc[i]
        stocks=0
        current=0
        buy=0
      elif(current==1):
        non_invested+=stocks*data_prices['Close'].iloc[i]
        stocks=0
        current=0
        buy=0
    elif(buy>0 and data_prices['Close'].iloc[i]<s_l*buy):
      if(current==-1):
        non_invested-=stocks*data_prices['Close'].iloc[i]
        stocks=0
        current=0
        buy=0
      elif(current==1):
        non_invested+=stocks*data_prices['Close'].iloc[i]
        stocks=0
        current=0
        buy=0
    elif((data_prices['Close'].iloc[i]>= (data_prices['s25'].iloc[i] + 2*data_prices['dev'].iloc[i]))and current==0):
      start=i
      current=-1
      value = non_invested/data_prices['Close'].iloc[i]
      result = math.floor(value)
      stocks= result
      buy=data_prices['Close'].iloc[i]
      non_invested += result*data_prices['Close'].iloc[i]
    elif((data_prices['Close'].iloc[i]< (data_prices['s25'].iloc[i] - 2*data_prices['dev'].iloc[i]))and current==0):
      start=i
      current=1
      value = non_invested/data_prices['Close'].iloc[i]
      result = math.floor(value)
      stocks= result
      buy=data_prices['Close'].iloc[i]
      non_invested -= result*data_prices['Close'].iloc[i]
    elif((data_prices['Close'].iloc[i]< (data_prices['s25'].iloc[i] - 2*data_prices['dev'].iloc[i]))and current==-1):
      non_invested-=stocks*data_prices['Close'].iloc[i]
      stocks=0
      current=0
    elif((data_prices['Close'].iloc[i]>= (data_prices['s25'].iloc[i] + 2*data_prices['dev'].iloc[i]))and current==1):
      non_invested+=stocks*data_prices['Close'].iloc[i]
      stocks=0
      current=0

  if(current==1):
   non_invested +=stocks*data_prices['Close'].iloc[end]
  if(current==-1):
   non_invested -=stocks*data_prices['Close'].iloc[end]

  return non_invested

In [ ]:
# note I would be following the dynamic testing and hence would be investing all of the money in one go
# i would have to skip the signals for the initial hundred days as that much time is required for e100 and s100 to start
#note that I am not taking the help of leverage in the trading process
#strategy A - Bollinger
# startegy B - MACD

strat = 2   #as starting strategy
signals=[]
strategy=[]
current=0
stocks=0
non_invested=10000
s2=0
s1=0
buy=0

for i in range(26):
      signals.append(0)
for i in range(26):
      strategy.append(0)
tc=0 #trade completed
end=100

for i in range(26,len(data_prices)):
  strategy.append(strat)
  if (strat==1):
     s1+=1
  else:
     s2+=1

  hit=0

  s=end+1
  if(strat==1):
   if((buy>0 and data_prices['Close'].iloc[i]>t_f*buy )and (current ==-1 or current==1)):
      hit+=1
      if(current==-1):
        end=i
        tc=1
        signals.append(1)
        buy=0
      elif(current==1):
        end=i
        tc=1
        signals.append(-1)
        buy=0
   elif((buy>0 and data_prices['Close'].iloc[i]<s_l*buy)and (current ==-1 or current==1)):
      hit+=1
      if(current==-1):
        end=i
        tc=1
        signals.append(1)
        buy=0
      elif(current==1):
        end=i
        tc=1
        signals.append(-1)
        buy=0
   elif((data_prices['macd'].iloc[i]>data_prices['e9'].iloc[i] and data_prices['macd'].iloc[i-1]<data_prices['e9'].iloc[i-1] )and current==0):
        start=i
        signals.append(1)
        current=1
        buy=data_prices['Close'].iloc[i]
   elif((data_prices['macd'].iloc[i]>data_prices['e9'].iloc[i] and data_prices['macd'].iloc[i-1]<data_prices['e9'].iloc[i-1] )and current==1):
        signals.append(0)      #######
   elif((data_prices['macd'].iloc[i]<data_prices['e9'].iloc[i] and data_prices['macd'].iloc[i-1]>data_prices['e9'].iloc[i-1] )and current==0):
        start=i
        signals.append(-1)
        current=-1
        buy=data_prices['Close'].iloc[i]
   elif((data_prices['macd'].iloc[i]<data_prices['e9'].iloc[i] and data_prices['macd'].iloc[i-1]>data_prices['e9'].iloc[i-1] )and current==-1):
        signals.append(0)       #######
   elif((data_prices['macd'].iloc[i]>data_prices['e9'].iloc[i] and data_prices['macd'].iloc[i-1]<data_prices['e9'].iloc[i-1] )and current==-1):
    end=i
    tc=1
    signals.append(1)
   elif((data_prices['macd'].iloc[i]<data_prices['e9'].iloc[i] and data_prices['macd'].iloc[i-1]>data_prices['e9'].iloc[i-1] )and current==1):
    end=i
    tc=1
    signals.append(-1)
   else:
    signals.append(0)

   if(tc==1):
    returns2=strat2(s,end,non_invested)
    if(current==1):
      value = non_invested/data_prices['Close'].iloc[start]
      result = math.floor(value)
      stocks= result
      non_invested -= result*data_prices['Close'].iloc[end]
    if(current==-1):
      value = non_invested/data_prices['Close'].iloc[start]
      result = math.floor(value)
      stocks= result
      non_invested += result*data_prices['Close'].iloc[end]

    current=0
    if(returns2>non_invested):
      strat=2
      tc=0
    else:
      tc=0

    continue

  if(strat==2):
    if((buy>0 and data_prices['Close'].iloc[i]>t_f*buy)and (current ==-1 or current==1)):
      if(current==-1):
        end=i
        tc=1
        signals.append(1)
        buy=0
      elif(current==1):
        end=i
        tc=1
        signals.append(-1)
        buy=0
    elif((buy>0 and data_prices['Close'].iloc[i]<s_l*buy)and (current ==-1 or current==1)):
      if(current==-1):
        end=i
        tc=1
        signals.append(1)
        buy=0
      elif(current==1):
        end=i
        tc=1
        signals.append(-1)
        buy=0
    elif((data_prices['Close'].iloc[i]>= (data_prices['s25'].iloc[i] + 2*data_prices['dev'].iloc[i]))and current==0):
      start=i
      signals.append(-1)
      current=-1
      buy=data_prices['Close'].iloc[i]
    elif((data_prices['Close'].iloc[i]>= (data_prices['s25'].iloc[i] + 2*data_prices['dev'].iloc[i]))and current==-1):
      signals.append(0)                 #######
    elif((data_prices['Close'].iloc[i]< (data_prices['s25'].iloc[i] - 2*data_prices['dev'].iloc[i]))and current==0):
      start=i
      signals.append(1)
      current=1
      buy=data_prices['Close'].iloc[i]
    elif((data_prices['Close'].iloc[i]< (data_prices['s25'].iloc[i] - 2*data_prices['dev'].iloc[i]))and current==1):
      signals.append(0)                 #######
    elif((data_prices['Close'].iloc[i]< (data_prices['s25'].iloc[i] - 2*data_prices['dev'].iloc[i]))and current==-1):
      end=i
      tc=1
      signals.append(1)
    elif((data_prices['Close'].iloc[i]>= (data_prices['s25'].iloc[i] + 2*data_prices['dev'].iloc[i]))and current==1):
      end=i
      tc=1
      signals.append(-1)
    else:
      signals.append(0)                #######

    if(tc==1):
     returns1=strat1(s,end,non_invested)
     if(current==1):
      value = non_invested/data_prices['Close'].iloc[start]
      result = math.floor(value)
      stocks= result
      non_invested -= result*data_prices['Close'].iloc[end]
     if(current==-1):
      value = non_invested/data_prices['Close'].iloc[start]
      result = math.floor(value)
      stocks= result
      non_invested += result*data_prices['Close'].iloc[end]

     current=0
     if(returns1>non_invested):
      strat=1
      tc=0
     else:
      tc=0





print(len(strategy))
print(s1)
print(s2)
print(hit)
data_prices["strategy"]= strategy
data_prices["signals"]= signals




## Following is the code which makes sure that the trade is closed
if(current==1):
  if(data_prices['signals'].iloc[-1]==1):
    data_prices['signals'].iloc[-1]=0
  else:
    data_prices['signals'].iloc[-1]=-1
elif(current==-1):
   if(data_prices['signals'].iloc[-1]==-1):
    data_prices['signals'].iloc[-1]=0
   else:
    data_prices['signals'].iloc[-1]=1



data_prices

1260
753
481
0

<ipython-input-24-dce343852d43>:193: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_prices['signals'].iloc[-1]=-1

,Date,Open,High,Low,Close,Adj Close,Volume,s12,s26,e12,e26,macd,s9,e9,s25,dev,strategy,signals
0,2019-05-16,33.660000,34.500000,33.080002,34.040001,34.040001,4267500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0,0
1,2019-05-17,33.560001,35.060001,33.500000,34.610001,34.610001,4496400,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0,0
2,2019-05-20,34.130001,34.689999,34.009998,34.660000,34.660000,2017000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0,0
3,2019-05-21,34.919998,35.290001,34.750000,34.860001,34.860001,2028200,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0,0
4,2019-05-22,34.750000,35.389999,34.669998,35.250000,35.250000,1726500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255,2024-05-10,49.110001,49.360001,48.549999,49.099998,49.099998,955200,47.681666,46.521923,47.893905,47.684343,0.209562,-0.434115,-1.023310,46.4792,1.746076,2,0
1256,2024-05-13,49.099998,49.669998,48.549999,48.570000,48.570000,967100,47.922500,46.559615,47.997920,47.749948,0.247972,-0.277041,-0.874056,46.5220,1.783291,2,0
1257,2024-05-14,49.110001,49.540001,48.689999,48.730000,48.730000,1290400,48.099166,46.606923,48.110548,47.822544,0.288003,-0.132206,-0.725686,46.5636,1.821768,2,0
1258,2024-05-15,48.779999,49.470001,48.240002,49.320000,49.320000,1255400,48.312500,46.669615,48.296617,47.933467,0.363150,-0.001182,-0.580785,46.6668,1.900224,2,0
1259,2024-05-16,49.680000,49.480000,49.020000,49.185001,49.185001,673154,48.558750,46.763654,48.433292,48.026173,0.407119,0.114028,-0.441822,46.7502,1.962153,2,-1

In [ ]:
count=0

for i in range(0,len(data_prices)):
  if(data_prices['signals'].iloc[i]==1 or data_prices['signals'].iloc[i]==-1 ):
    print(data_prices['signals'].iloc[i])
    count+=1

print(count/2)

-1
1
1
-1
-1
1
-1
1
1
-1
1
-1
-1
1
1
-1
1
-1
1
-1
1
-1
1
-1
1
-1
1
-1
1
-1
1
-1
1
-1
1
-1
1
-1
1
-1
1
-1
-1
1
1
-1
1
-1
1
-1
1
-1
-1
1
1
-1
-1
1
-1
1
1
-1
31.0

In [ ]:
portfolio_value=[]
stocks=0
non_invested_amount=10000
entry_index=0
exit_index=0
trade=0

for i in range(0,len(data_prices)):
  if(data_prices['signals'].iloc[i]==0):
    if(trade==-1 and (non_invested_amount - stocks*(data_prices['Close'].iloc[i]))<0):
      print("Capital Wiped Off")
      break
    else:
      portfolio_value.append(non_invested_amount + stocks*trade*(data_prices['Close'].iloc[i]))
      continue
  elif(trade==0 and data_prices['signals'].iloc[i]==1):
    entry_index=i
    value = non_invested_amount/data_prices['Close'].iloc[i]
    result = math.floor(value)
    stocks= result
    non_invested_amount -= result*data_prices['Close'].iloc[i]
    trade=1
    portfolio_value.append(non_invested_amount + stocks*trade*(data_prices['Close'].iloc[i]))
  elif(trade==0 and data_prices['signals'].iloc[i]==-1):
    entry_index=i
    value = non_invested_amount/data_prices['Close'].iloc[i]
    result = math.floor(value)
    stocks= result
    non_invested_amount += result*data_prices['Close'].iloc[i]
    trade=-1
    portfolio_value.append(non_invested_amount + stocks*trade*(data_prices['Close'].iloc[i]))
  elif(data_prices['signals'].iloc[i]==-1 and trade==1):
    exit_index=i
    trade=0
    non_invested_amount+=stocks*data_prices['Close'].iloc[exit_index]
    stocks=0
    portfolio_value.append(non_invested_amount + stocks*trade*(data_prices['Close'].iloc[i]))
  elif(data_prices['signals'].iloc[i]==1 and trade==-1):
    exit_index=i
    trade=0
    non_invested_amount-=stocks*data_prices['Close'].iloc[exit_index]
    stocks=0
    portfolio_value.append(non_invested_amount + stocks*trade*(data_prices['Close'].iloc[i]))

print(len(portfolio_value))

1260

In [ ]:
data_prices["portfolio_value"]=portfolio_value
data_prices

,Date,Open,High,Low,Close,Adj Close,Volume,s12,s26,e12,e26,macd,s9,e9,s25,dev,strategy,signals,portfolio_value
0,2019-05-16,33.660000,34.500000,33.080002,34.040001,34.040001,4267500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0,0,10000.000000
1,2019-05-17,33.560001,35.060001,33.500000,34.610001,34.610001,4496400,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0,0,10000.000000
2,2019-05-20,34.130001,34.689999,34.009998,34.660000,34.660000,2017000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0,0,10000.000000
3,2019-05-21,34.919998,35.290001,34.750000,34.860001,34.860001,2028200,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0,0,10000.000000
4,2019-05-22,34.750000,35.389999,34.669998,35.250000,35.250000,1726500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0,0,10000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255,2024-05-10,49.110001,49.360001,48.549999,49.099998,49.099998,955200,47.681666,46.521923,47.893905,47.684343,0.209562,-0.434115,-1.023310,46.4792,1.746076,2,0,26497.633097
1256,2024-05-13,49.099998,49.669998,48.549999,48.570000,48.570000,967100,47.922500,46.559615,47.997920,47.749948,0.247972,-0.277041,-0.874056,46.5220,1.783291,2,0,26211.964175
1257,2024-05-14,49.110001,49.540001,48.689999,48.730000,48.730000,1290400,48.099166,46.606923,48.110548,47.822544,0.288003,-0.132206,-0.725686,46.5636,1.821768,2,0,26298.204175
1258,2024-05-15,48.779999,49.470001,48.240002,49.320000,49.320000,1255400,48.312500,46.669615,48.296617,47.933467,0.363150,-0.001182,-0.580785,46.6668,1.900224,2,0,26616.214175
1259,2024-05-16,49.680000,49.480000,49.020000,49.185001,49.185001,673154,48.558750,46.763654,48.433292,48.026173,0.407119,0.114028,-0.441822,46.7502,1.962153,2,-1,26543.449714

In [ ]:
import math


stocks = 0
non_invested_amount = 10000
entry_index=0
exit_index=0
trade=0

trade_df = pd.DataFrame(columns=['entry_index', 'exit_index', 'entry_date', 'exit_date' , 'Trade_duration','Returns','Type of trade','Drawdown','Max_Dip','Quantity of stocks traded'])

trade_df

Empty DataFrame
Columns: [entry_index, exit_index, entry_date, exit_date, Trade_duration, Returns, Type of trade, Drawdown, Max_Dip, Quantity of stocks traded]
Index: []

In [ ]:
daily_df = pd.DataFrame(columns=['Date','Portfolio_value', 'Max_of_portfolio_value_yet', 'stocks_held', 'Profit_from_initial_capital'])

daily_df

Empty DataFrame
Columns: [Date, Portfolio_value, Max_of_portfolio_value_yet, stocks_held, Profit_from_initial_capital]
Index: []

In [ ]:
for i in range(0,len(data_prices)):
  if(data_prices['signals'].iloc[i]==0):
    if(trade==-1 and (non_invested_amount - stocks*(data_prices['Close'].iloc[i]))<0):
      print("Capital Wiped Off")
      break
    else:
      new_entry = {'Date': data_prices['Date'].iloc[i],'Portfolio_value': non_invested_amount + stocks*trade*(data_prices['Close'].iloc[i]) , 'stocks_held':stocks}
      daily_df.loc[len(daily_df)] = new_entry
      continue
  elif(trade==0 and data_prices['signals'].iloc[i]==1):
    entry_index=i
    value = non_invested_amount/data_prices['Close'].iloc[i]
    result = math.floor(value)
    stocks= result
    non_invested_amount -= result*data_prices['Close'].iloc[i]
    trade=1
    new_entry = {'Date': data_prices['Date'].iloc[i],'Portfolio_value': non_invested_amount + stocks*trade*(data_prices['Close'].iloc[i]) , 'stocks_held':stocks}
    daily_df.loc[len(daily_df)] = new_entry
  elif(trade==0 and data_prices['signals'].iloc[i]==-1):
    entry_index=i
    value = non_invested_amount/data_prices['Close'].iloc[i]
    result = math.floor(value)
    stocks= result
    non_invested_amount += result*data_prices['Close'].iloc[i]
    trade=-1
    new_entry = {'Date': data_prices['Date'].iloc[i],'Portfolio_value': non_invested_amount + stocks*trade*(data_prices['Close'].iloc[i]) , 'stocks_held':stocks}
    daily_df.loc[len(daily_df)] = new_entry
  elif(data_prices['signals'].iloc[i]==-1 and trade==1):
    exit_index=i
    new_entry = {'entry_index': entry_index, 'exit_index': exit_index ,'entry_date': data_prices['Date'].iloc[entry_index] ,'exit_date': data_prices['Date'].iloc[exit_index], 'Trade_duration': exit_index-entry_index , 'Type of trade':trade , 'Quantity of stocks traded':stocks, 'Returns':stocks*trade*(data_prices['Close'].iloc[exit_index]-data_prices['Close'].iloc[entry_index]) }
    trade_df.loc[len(trade_df)] = new_entry
    trade=0
    non_invested_amount+=stocks*data_prices['Close'].iloc[exit_index]
    stocks=0
    new_entry = {'Date': data_prices['Date'].iloc[i],'Portfolio_value': non_invested_amount + stocks*trade*(data_prices['Close'].iloc[i]) , 'stocks_held':stocks}
    daily_df.loc[len(daily_df)] = new_entry
  elif(data_prices['signals'].iloc[i]==1 and trade==-1):
    exit_index=i
    new_entry = {'entry_index': entry_index, 'exit_index': exit_index ,'entry_date': data_prices['Date'].iloc[entry_index] ,'exit_date': data_prices['Date'].iloc[exit_index], 'Trade_duration': exit_index-entry_index , 'Type of trade': trade , 'Quantity of stocks traded':stocks, 'Returns':stocks*trade*(data_prices['Close'].iloc[exit_index]-data_prices['Close'].iloc[entry_index]) }
    trade_df.loc[len(trade_df)] = new_entry
    trade=0
    non_invested_amount-=stocks*data_prices['Close'].iloc[exit_index]
    stocks=0
    new_entry = {'Date': data_prices['Date'].iloc[i],'Portfolio_value': non_invested_amount + stocks*trade*(data_prices['Close'].iloc[i]) , 'stocks_held':stocks}
    daily_df.loc[len(daily_df)] = new_entry

In [ ]:
trade_df

,entry_index,exit_index,entry_date,exit_date,Trade_duration,Returns,Type of trade,Drawdown,Max_Dip,Quantity of stocks traded
0,48,55,2019-07-25,2019-08-05,7,957.029781,-1,NaN,NaN,219
1,63,146,2019-08-15,2019-12-12,83,696.149727,1,NaN,NaN,273
2,163,189,2020-01-08,2020-02-14,26,-250.250000,-1,NaN,NaN,275
3,192,195,2020-02-20,2020-02-25,3,906.240256,-1,NaN,NaN,256
4,217,245,2020-03-26,2020-05-06,28,1477.910000,1,NaN,NaN,301
5,253,267,2020-05-18,2020-06-08,14,844.199196,1,NaN,NaN,268
6,286,324,2020-07-06,2020-08-27,38,149.639484,-1,NaN,NaN,258
7,346,413,2020-09-29,2021-01-05,67,4140.178893,1,NaN,NaN,369
8,460,484,2021-03-15,2021-04-19,24,-499.149330,1,NaN,NaN,335
9,507,527,2021-05-20,2021-06-18,20,942.560688,1,NaN,NaN,344
10,555,565,2021-07-29,2021-08-12,10,-559.449330,1,NaN,NaN,335
11,575,585,2021-08-26,2021-09-10,10,-930.110331,1,NaN,NaN,331
12,602,637,2021-10-05,2021-11-23,35,2872.400688,1,NaN,NaN,344
13,648,665,2021-12-09,2022-01-04,17,1137.599136,1,NaN,NaN,288
14,694,707,2022-02-15,2022-03-07,13,-3116.630319,1,NaN,NaN,319
15,720,733,2022-03-24,2022-04-12,13,-1250.220000,1,NaN,NaN,311
16,741,743,2022-04-25,2022-04-27,2,-905.970303,1,NaN,NaN,303
17,744,751,2022-04-28,2022-05-09,7,-1501.560000,1,NaN,NaN,291
18,765,773,2022-05-27,2022-06-09,8,-1604.161152,1,NaN,NaN,288
19,783,825,2022-06-24,2022-08-24,42,2031.960287,1,NaN,NaN,287
20,850,880,2022-09-29,2022-11-10,30,1235.000000,1,NaN,NaN,380
21,899,941,2022-12-08,2023-02-09,42,1020.680000,-1,NaN,NaN,323
22,956,971,2023-03-03,2023-03-24,15,50.680000,1,NaN,NaN,362
23,974,986,2023-03-29,2023-04-17,12,-582.960347,1,NaN,NaN,347
24,1008,1023,2023-05-17,2023-06-08,15,-762.390387,1,NaN,NaN,387
25,1070,1080,2023-08-16,2023-08-30,10,1113.840000,1,NaN,NaN,408
26,1081,1105,2023-08-31,2023-10-05,24,2192.960000,-1,NaN,NaN,352
27,1111,1133,2023-10-13,2023-11-14,22,1728.569058,1,NaN,NaN,471
28,1134,1156,2023-11-15,2023-12-18,22,1521.919072,-1,NaN,NaN,464
29,1169,1235,2024-01-08,2024-04-12,66,869.940486,-1,NaN,NaN,486
30,1236,1259,2024-04-15,2024-05-16,23,2616.844461,1,NaN,NaN,539

In [ ]:
non_invested_amount

26543.449713999984

In [ ]:
Total = sum(trade_df['Returns'])
Total

16543.44971399999

In [ ]:
print(10000+Total)

26543.44971399999

In [ ]:
daily_df

,Date,Portfolio_value,Max_of_portfolio_value_yet,stocks_held,Profit_from_initial_capital
0,2019-05-16,10000.000000,NaN,0,NaN
1,2019-05-17,10000.000000,NaN,0,NaN
2,2019-05-20,10000.000000,NaN,0,NaN
3,2019-05-21,10000.000000,NaN,0,NaN
4,2019-05-22,10000.000000,NaN,0,NaN
...,...,...,...,...,...
1255,2024-05-10,26497.633097,NaN,539,NaN
1256,2024-05-13,26211.964175,NaN,539,NaN
1257,2024-05-14,26298.204175,NaN,539,NaN
1258,2024-05-15,26616.214175,NaN,539,NaN
1259,2024-05-16,26543.449714,NaN,0,NaN

In [ ]:
for i in range(0,len(trade_df)):
  entry_price=daily_df['Portfolio_value'].iloc[trade_df['entry_index'].iloc[i]]
  max=entry_price
  drawdown=0
  max_drawdown=0
  min_portfolio=entry_price
  for j in range(trade_df['entry_index'].iloc[i]+1,trade_df['exit_index'].iloc[i]+1):
    if(daily_df['Portfolio_value'].iloc[j]>max):
      max=daily_df['Portfolio_value'].iloc[j]
    if(daily_df['Portfolio_value'].iloc[j]<min_portfolio):
      min_portfolio=daily_df['Portfolio_value'].iloc[j]
    drawdown=((max-daily_df['Portfolio_value'].iloc[j])/max)*100
    if(drawdown>max_drawdown):
      max_drawdown=drawdown
  max_dip = ((entry_price - min_portfolio)/entry_price)*100
  trade_df['Drawdown'].iloc[i]=max_drawdown
  trade_df['Max_Dip'].iloc[i]=max_dip

<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip
<ipython-input-36-00ab6501df94>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Drawdown'].iloc[i]=max_drawdown
<ipython-input-36-00ab6501df94>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trade_df['Max_Dip'].iloc[i]=max_dip

In [ ]:
trade_df

,entry_index,exit_index,entry_date,exit_date,Trade_duration,Returns,Type of trade,Drawdown,Max_Dip,Quantity of stocks traded
0,48,55,2019-07-25,2019-08-05,7,957.029781,-1,0.722704,0.722704,219
1,63,146,2019-08-15,2019-12-12,83,696.149727,1,17.782776,13.603867,273
2,163,189,2020-01-08,2020-02-14,26,-250.250000,-1,6.388517,2.831848,275
3,192,195,2020-02-20,2020-02-25,3,906.240256,-1,0.000000,0.000000,256
4,217,245,2020-03-26,2020-05-06,28,1477.910000,1,6.491875,3.643549,301
5,253,267,2020-05-18,2020-06-08,14,844.199196,1,4.202554,0.369337,268
6,286,324,2020-07-06,2020-08-27,38,149.639484,-1,14.166032,7.793991,258
7,346,413,2020-09-29,2021-01-05,67,4140.178893,1,10.650471,3.869523,369
8,460,484,2021-03-15,2021-04-19,24,-499.149330,1,8.247481,6.834172,335
9,507,527,2021-05-20,2021-06-18,20,942.560688,1,7.584687,1.008364,344
10,555,565,2021-07-29,2021-08-12,10,-559.449330,1,3.738349,2.889045,335
11,575,585,2021-08-26,2021-09-10,10,-930.110331,1,7.849442,4.946064,331
12,602,637,2021-10-05,2021-11-23,35,2872.400688,1,3.197332,0.365649,344
13,648,665,2021-12-09,2022-01-04,17,1137.599136,1,2.213376,0.000000,288
14,694,707,2022-02-15,2022-03-07,13,-3116.630319,1,16.255107,14.240976,319
15,720,733,2022-03-24,2022-04-12,13,-1250.220000,1,9.013335,6.661332,311
16,741,743,2022-04-25,2022-04-27,2,-905.970303,1,5.171625,5.171625,303
17,744,751,2022-04-28,2022-05-09,7,-1501.560000,1,9.734674,9.038938,291
18,765,773,2022-05-27,2022-06-09,8,-1604.161152,1,10.616154,10.616154,288
19,783,825,2022-06-24,2022-08-24,42,2031.960287,1,4.159979,3.017381,287
20,850,880,2022-09-29,2022-11-10,30,1235.000000,1,14.678955,4.108540,380
21,899,941,2022-12-08,2023-02-09,42,1020.680000,-1,6.518609,0.308107,323
22,956,971,2023-03-03,2023-03-24,15,50.680000,1,4.365286,0.610314,362
23,974,986,2023-03-29,2023-04-17,12,-582.960347,1,5.472610,3.266849,347
24,1008,1023,2023-05-17,2023-06-08,15,-762.390387,1,11.900311,4.730514,387
25,1070,1080,2023-08-16,2023-08-30,10,1113.840000,1,2.141848,0.000000,408
26,1081,1105,2023-08-31,2023-10-05,24,2192.960000,-1,2.516305,0.000000,352
27,1111,1133,2023-10-13,2023-11-14,22,1728.569058,1,7.508314,3.329269,471
28,1134,1156,2023-11-15,2023-12-18,22,1521.919072,-1,5.619471,1.206612,464
29,1169,1235,2024-01-08,2024-04-12,66,869.940486,-1,31.807465,31.807465,486
30,1236,1259,2024-04-15,2024-05-16,23,2616.844461,1,3.260089,1.734599,539

CLEARLY THE TOTAL NUMBER OF CLOSED TRADES ARE 90

In [ ]:
winning_trades=0
losing_trades=0

for i in range(0,len(trade_df)):
  if(trade_df["Returns"].iloc[i]>=0):
    winning_trades+=1
  elif(trade_df["Returns"].iloc[i]<0):
    losing_trades+=1

winning_trades

20

In [ ]:
losing_trades

11

In [ ]:
total_trades = winning_trades + losing_trades
total_trades

31

In [ ]:
max_drawdown = trade_df['Drawdown'].max()
max_drawdown

31.807464609957236

In [ ]:
gross_profit =0
gross_loss=0
for i in range(0,len(trade_df)):
  if(trade_df["Returns"].iloc[i]>0):
    gross_profit+=trade_df["Returns"].iloc[i]
  else:
    gross_loss+=trade_df["Returns"].iloc[i]

gross_loss -= 20*total_trades

In [ ]:
total_net_profit= gross_profit + gross_loss
total_net_profit

15923.449714000004

In [ ]:
profit_factor = -(gross_profit/gross_loss)
profit_factor

2.2654881697734

In [ ]:
percent_profitable = winning_trades/total_trades
percent_profitable

0.6451612903225806

In [ ]:
Average_Trade_Net_Profit = total_net_profit/total_trades
Average_Trade_Net_Profit

513.6596681935486

In [ ]:
print("RESULTS")
print(f"final amount : {non_invested_amount}\n  bechmark_return_value : {benchmark_value} \ntotal_trades: {total_trades} \nwinning_trades:{winning_trades}\n losing_trades:{losing_trades} \n total_net_profit:{total_net_profit} ")
print(f"profit_factor : {profit_factor } \npercent_profitable: {percent_profitable} \n Average_Trade_Net_Profit :{Average_Trade_Net_Profit}\n maximum Drawdown : {max_drawdown} ")

RESULTS
final amount : 26543.449713999984
  bechmark_return_value : 4449.177307603488
total_trades: 31
winning_trades:20
 losing_trades:11
 total_net_profit:15923.449714000004
profit_factor : 2.2654881697734
percent_profitable: 0.6451612903225806
 Average_Trade_Net_Profit :513.6596681935486
 maximum Drawdown : 31.807464609957236